class Config:
    def __init__(self):
        pass

    DATE_RANGE_TYPE_OPEN = 62
    DATE_RANGE_TYPE_CLOSED = 63
    DATE_RANGE_TYPE_PRICE_MODIFIER = 164

    PRICE_MODIFIER_CALCULATIONS_BASE_TX_ID = 319
    MERGED_FREE_NIGHTS_TX_ID = 334

    PRICE_MODIFIER_TYPE_DISCOUNT = 491
    PRICE_MODIFIER_TYPE_RULE = 492
    PRICE_MODIFIER_TYPE_SWITCH = 493

    ORGANIZATION_STRICT_CHILD_BED_POLICY_TAXONOMY_ID = 499
    ORGANIZATION_STRICT_CHILD_BED_POLICY_ENABLED_TAXONOMY_ID = 502

    DEVICE_STRICT_CHILD_BED_POLICY_TAXONOMY_ID = 498
    DEVICE_STRICT_CHILD_BED_POLICY_ENABLED_TAXONOMY_ID = 500

    PRODUCT_TYPE_ACCOMMODATION_TX_ID = 60
    PRODUCT_TYPE_PRICE_MODIFIED_ACCOMMODATION_TX_ID = 299
