<?php

namespace Tests\Integration\Manipulators;

use App\Manipulators\PriceImportSetter;
use Tests\TestCase;

class PriceImportSetterTest extends TestCase
{
    /**
     * @test
     */
    function constructorTest() {
        $priceImportSetter = new PriceImportSetter();
        $this->assertInstanceOf('App\Manipulators\PriceImportSetter', $priceImportSetter);
    }

    /**
     * @test
     * @throws \App\Exceptions\UserException
     */
    function savePriceElementsTest() {
        $response = PriceImportSetter::savePriceElements($this->getTestPriceList());
        $this->assertTrue($response);
    }

    private function getTestPriceList() {
        return [
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"4",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"14",
                    "net_price"=>"80",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"4",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"15",
                    "net_price"=>"90",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>true,
                    "price_id"=>"4",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"16",
                    "net_price"=>"0",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>false,
                    "price_id"=>"4",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"22",
                    "net_price"=>"0",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"4",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"17",
                    "net_price"=>"80",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"4",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"18",
                    "net_price"=>"81",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"14",
                    "net_price"=>"4.1",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"15",
                    "net_price"=>"50",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"16",
                    "net_price"=>"40",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"22",
                    "net_price"=>"130",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>17,
                    "net_price"=>"40",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"5",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"18",
                    "net_price"=>"41",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"6",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"14",
                    "net_price"=>"30",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"6",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"15",
                    "net_price"=>"11",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>false,
                    "price_id"=>"6",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"16",
                    "net_price"=>"0",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>false,
                    "price_id"=>"6",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"22",
                    "net_price"=>"0",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"6",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"17",
                    "net_price"=>"10",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"6",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"18",
                    "net_price"=>"111",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"11",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"14",
                    "net_price"=>"9.1",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"9",
                    "enabled"=>true,
                    "price_id"=>"11",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"15",
                    "net_price"=>"90",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>true,
                    "price_id"=>"11",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"16",
                    "net_price"=>"100",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"10",
                    "enabled"=>false,
                    "price_id"=> "11",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"22",
                    "net_price"=>"0",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"11",
                    "meal_plan"=>"b/b",
                    "model_meal_plan_id"=>"17",
                    "net_price"=>"100",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ],
                [
                    "date_range_id"=>"11",
                    "enabled"=>true,
                    "price_id"=>"11",
                    "meal_plan"=>"h/b",
                    "model_meal_plan_id"=>"18",
                    "net_price"=>"100",
                    "rack_price"=>null,
                    "margin_type_taxonomy_id"=>"57",
                ]
        ];
    }


}
